name: caller-workflow
run-name: Test environment - caller
on:
  workflow_dispatch:

jobs:
  call-workflow-2-in-local-repo:
    uses: ezmamig/testni-repo/.github/workflows/callable2.yml@master
    with:
      tpt_file_name: "tptConfig1.json, tptConfig2.json"
    secrets:
      envPAT: envPath
