name: callable-workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_call:
    inputs:
      tpt_file_name:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
env:
  tpt_file_name:  ${{ inputs.tpt_file_name }}
  tpt_file_path: "${{ github.workspace }}\\tests\\Tpt\\"

jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - uses: ezmamig/avl_tehnicki_zadatak/run-tpt-action@master
        with:
            tptFileName: ${{ env.tpt_file_name }}
            tptFilePath: ${{ env.tpt_file_path }}