name: caller-workflow
run-name: Test environment - caller
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkoutRepo:

    runs-on: [windows-latest]

    ##### Define the job outputs #####
    outputs:
      supported_os: ${{ steps.read-supportedos.outputs.supported_os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Read SupportedOS from JSON
        id: read-supportedos
        run: |
          $file_path="${{ github.workspace }}/tptConfig/installCFG.json"
          
          $jsonContent = Get-Content -Path $file_path -Raw
          $jsonObject = ConvertFrom-Json -InputObject $jsonContent

          # Obtain the value for the key "SupportedOS"
          $supportedOs = $jsonObject.SupportedOS -join ', '
          $supportedOsArray = @($supportedOs -split ',\s*' | ForEach-Object { "$_" })
          $supportedOsJson = ConvertTo-Json $supportedOsArray -Compress -Depth 100 | Out-String
          echo $supportedOsJson
          
          echo "supported_os=$supportedOsJson" >> $env:GITHUB_OUTPUT
        shell: powershell

  call-workflow-2-in-local-repo:
    needs: [checkoutRepo]
    strategy:
      matrix:
        target: ${{ fromJson(needs.checkoutRepo.outputs.supported_os) }}
    uses: ezmamig/testni-repo/.github/workflows/callable2.yml@master
    with:
      tpt_file_name: "tptConfig1.json, tptConfig2.json"
      target: ${{ matrix.target }}
    secrets:
      envPAT: envPath

  tempJob:
    needs: [call-workflow-2-in-local-repo]
    runs-on: [ubuntu-latest]
    steps:
      - name: Debug matrix functionality
        run: echo "tempJob output"
