name: caller-workflow
run-name: ${{ github.actor }} is learning GitHub Actions - caller
on:
  workflow_dispatch:

jobs:
  call-workflow-2-in-local-repo:
    uses: ezmamig/testni-repo/.github/workflows/callable.yaml@master
    with:
      config-path: DemoConfig
    secrets:
      envPAT: envPath
