name: callable-workflow
run-name: Test environment - callable
on:
  workflow_call:
    inputs:
      tpt_file_name:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
env:
  tpt_file_name:  ${{ inputs.tpt_file_name }}
  tpt_file_path: "${{ github.workspace }}\\tests\\Tpt\\"

jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - name: Run Tpt Action
        uses: ezmamig/avl_tehnicki_zadatak/run-tpt-action@master
        with:
            tptFileName: ${{ env.tpt_file_name }}
            tptFilePath: ${{ env.tpt_file_path }}
      - name: Use TPT Test Runner with ALMConnector
        uses: ezmamig/avl_tehnicki_zadatak/run-TPT-testrunner-ALMConnector@master
        with:
          tptFileName: ${{ env.tpt_file_name }}
          tptFilePath: ${{ env.tpt_file_path }}