name: callable-workflow
run-name: Test environment - callable
on:
  workflow_call:
    inputs:
      tpt_file_name:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
env:
  tpt_file_name:  ${{ inputs.tpt_file_name }}
  tpt_file_path: "${{ github.workspace }}\\tptConfig\\"

jobs:
  generateMatrix:
    name: Generate matrix
    runs-on: windows-latest
    steps:
      - name: Set up matrix
        id: set-up-matrix
        run: |
          $helper = "${{ env.tpt_file_name }}"
          $tpt_file_name_array = @($helper -split ',\s*' | ForEach-Object { "$_" })
          $tpt_file_name_json = ConvertTo-Json $tpt_file_name_array -Compress -Depth 100 | Out-String
          "tpt_file_name_json=$tpt_file_name_json" >> $env:GITHUB_OUTPUT
        shell: powershell
    outputs:
      tpt_file_name: ${{ steps.set-up-matrix.outputs.tpt_file_name_json }}
  check-bats-version:
    runs-on: windows-latest
    needs: [generateMatrix]
    strategy:
      fail-fast: false
      matrix: 
        tptFile: ${{ fromJson(needs.generateMatrix.outputs.tpt_file_name) }}
    steps:
      - name: Debug matrix functionality
        uses: actions/checkout@v1
      - name: Run Tpt Action
        uses: ezmamig/avl_tehnicki_zadatak/run-tpt-action@master
        with:
            tptFileName: ${{ matrix.tptFile }}
            tptFilePath: ${{ env.tpt_file_path }}
      - name: Remove extension from tpt file
        id: remove-extension
        run: |
          $pos = ${{ matrix.tptFile }}.IndexOf(".")
          $baseName = ${{ matrix.tptFile }}.Substring(0, $pos)
          echo "::set-output name=tptFileNoExtension::$baseName"
      - name: Use TPT Test Runner with ALMConnector
        uses: ezmamig/avl_tehnicki_zadatak/run-TPT-testrunner-ALMConnector@master
        with:
          tptFileName: ${{ matrix.tptFile }}
          tptFileNoExtension: ${{ steps.remove-extension.outputs.tptFileNoExtension }}
          tptFilePath: ${{ env.tpt_file_path }}