name: caller-workflow
run-name: ${{ github.actor }} is learning GitHub Actions - caller
on:
  workflow_dispatch:

jobs:
  call-workflow-2-in-local-repo:
    uses: ezmamig/testni-repo/.github/workflows/callable.yaml@master
    with:
      tpt_file_name: "Tpt_Swc1.tptz" 
    secrets:
      envPAT: envPath
