name: callable-workflow
run-name: Test environment - callable
on:
  workflow_call:
    inputs:
      tpt_file_name:
        required: true
        type: string
      target:
        required: false
        type: string
    secrets:
      envPAT:
        required: true
env:
  tpt_file_name:  ${{ inputs.tpt_file_name }}
  tpt_file_path: "${{ github.workspace }}\\tptConfig\\"

jobs:
  example_matrix:
    runs-on: [ubuntu-latest]
    steps:
      - name: Debug matrix functionality
        uses: actions/checkout@v1

      - name: Fail prod case
        run: |
          if [[ ${{ inputs.target }} == "prod" ]]; then
            exit 1
