name: callable-workflow
run-name: Test environment - callable
on:
  workflow_call:
    inputs:
      tpt_file_name:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
env:
  tpt_file_name:  ${{ inputs.tpt_file_name }}
  tpt_file_path: "${{ github.workspace }}\\tptConfig\\"

jobs:
  generateMatrix:
    name: Generate matrix
    runs-on: windows-latest
    steps:
      - name: Set up matrix
        id: set-up-matrix
        run: |
          $helper = "${{ env.tpt_file_name }}"
          $tpt_file_name_array = @($helper -split ',\s*' | ForEach-Object { "$_" })
          $tpt_file_name_json = $tpt_file_name_array | ConvertTo-Json -Compress -Depth 100 | Out-String
          Write-Output "matrix=$tpt_file_name_json" >> $GITHUB_OUTPUT
        shell: powershell
  check-bats-version:
    runs-on: windows-latest
    needs: [generateMatrix]
    strategy:
      fail-fast: false
      matrix: 
        tptFiles: ${{ fromJson(needs.generateMatrix.set-up-matrix.outputs.matrix) }}
    steps:
      - name: Debug matrix functionality
        uses: actions/checkout@v1
      - name: Run Tpt Action
        uses: ezmamig/avl_tehnicki_zadatak/run-tpt-action@master
        with:
            tptFileName: ${{ matrix.tptFiles }}
            tptFilePath: ${{ env.tpt_file_path }}
      - name: Use TPT Test Runner with ALMConnector
        uses: ezmamig/avl_tehnicki_zadatak/run-TPT-testrunner-ALMConnector@master
        with:
          tptFileName: ${{ matrix.tptFiles }}
          tptFilePath: ${{ env.tpt_file_path }}