name: callable-workflow
run-name: Test environment - callable
on:
  workflow_call:
    inputs:
      tpt_file_name:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
env:
  tpt_file_name:  ${{ inputs.tpt_file_name }}
  tpt_file_path: "${{ github.workspace }}\\tptConfig\\"

jobs:
  generateMatrix:
    name: Generate matrix
    runs-on: windows-latest
    outputs:
      matrix: ${{ steps.set-up-matrix.outputs.matrix }}
    steps:
      - name: check out source
        uses: actions/checkout@v1
      - name: Set up matrix
        id: set-up-matrix
        run: |
          ls ${{ env.tpt_file_path }}
          $matrix = (cat ${{ env.tpt_file_path }}${{ env.tpt_file_name }})
          echo "[Info] Matrix JSON:"
          echo $matrix
          echo "::set-output name=matrix::$matrix"
        shell: powershell
  check-bats-version:
    runs-on: windows-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix: 
        tptFiles: ${{ fromJson(needs.generateMatrix.outputs.matrix).tptFiles }}
    needs: [generateMatrix]
    steps:
      - name: Run Tpt Action
        uses: ezmamig/avl_tehnicki_zadatak/run-tpt-action@master
        with:
            tptFileName: ${{ matrix.tptFiles.tptFile }}
            tptFilePath: ${{ env.tpt_file_path }}
      - name: Use TPT Test Runner with ALMConnector
        uses: ezmamig/avl_tehnicki_zadatak/run-TPT-testrunner-ALMConnector@master
        with:
          tptFileName: ${{ matrix.tptFiles.tptFile }}
          tptFilePath: ${{ env.tpt_file_path }}