name: caller-workflow
run-name: Test environment - caller
on:
  workflow_dispatch:

jobs:
  call-workflow-2-in-local-repo:
    uses: ezmamig/testni-repo/.github/workflows/callable.yaml@master
    with:
      tpt_file_name: "tptConfigs.json" 
    secrets:
      envPAT: envPath
